version: '3'

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_DB=records_store
      - POSTGRES_USER=records_store
      - POSTGRES_PASSWORD=some_password
      - PGDATA=/tmp
    volumes:
      - /postgres-data:/var/lib/postgresql/data
  
  flask_app:
    build: .
    container_name: flask_app
    restart: always
    depends_on: 
      - postgres_db
    environment:
      db_user: records_store
      db_password: some_password
    ports: 
      - "8000:5000"

volumes:
  postgres-data:
